version: '3.9'
services:
  main:
    image: code_wars_solver:local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code_wars_solver/app
    environment:
      - HEADLESS_BROWSER=true
    ports:
      - "8000:8000"
    env_file:
      - local.env
