version: '3.9'
services:
  tests:
    image: code_wars_gpt:tests
    command: "pytest -v --junitxml=reports/results.xml --cov-report=xml:reports/coverage.xml --cov=."
    working_dir: "/code_wars_gpt"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code_wars_gpt/app
      - ./tests:/code_wars_gpt/tests
      - ./reports:/code_wars_gpt/reports
    environment:
      - STAGE=tests
