[tool.poetry]
name = "code_wars_gpt"
version = "0.1.0"
description = "Use chatGPT to solve code katas from code wars"
authors = ["Maxime Houé <maxhoue@gmail.com>"]
readme = "README.md"
repository = "https://github.com/maxime-houe/code_wars_gpt"

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"
langchain = "^0.0.338"
openai = "^1.3.5"
pydantic = "^2.5.2"
pydantic-settings = "^2.0.3"
selenium = "^4.15.2"
tiktoken = "^0.5.1"
uvicorn = "^0.24.0"


[tool.poetry.group.tests.dependencies]
hypothesis = "^6.90.0"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"


[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
python-semantic-release = "^8.3.0"

[tool.pytest.ini_options]
python_files = ["*_test.py"]
markers = [
    "integration",
    "unit",
]

[tool.semantic_release]
version_variables = [
    "app/config.py:__version__",
]
version_toml = [
    "pyproject.toml:tool.poetry.version",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
