name: On pull request commit

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
#  test:
#    runs-on: self-hosted
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          fetch-depth: 0
#
#      - name: "Set up docker"
#        uses: docker/setup-buildx-action@v2
#
#      - name: "Build docker with cache"
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: false
#          load: true
#          target: tests
#          tags: astrolo:tests
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
#          build-args: |
#            PACKAGES_GITHUB_TOKEN=${{ secrets.PACKAGES_GITHUB_TOKEN }}
#
#      - name: "Run docker compose tests with cache"
#        run: docker-compose --file docker-compose.tests.yml up --no-build --abort-on-container-exit


  code-style-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v3

      - name: "Set up python and pip"
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: "Install black"
        run: |
          pip install --upgrade pip
          pip install black

      - name: "Black linter check"
        run: |
          black --check .

#  semantic-release:
#    runs-on: ubuntu-latest
#    concurrency: release
#    permissions:
#      id-token: write
#      contents: write
#
#    steps:
#    - uses: actions/checkout@v3
#      with:
#        fetch-depth: 0
#
#    - name: Python Semantic Release
#      uses: python-semantic-release/python-semantic-release@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
